name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Change directory to bin folder
      run: cd bin
    - name: Run pnbTransactionVerifierForAccountLedger.dart
      run: dart pnbTransactionVerifierForAccountLedger.dart
